### PR TITLE
Rebase and fix

### PR DESCRIPTION
**Pull request by xamanu**
Hi Nico,

here are some minor things I made to test this:

* rebased on the latest master from the upstream repository (`grote/osm2gtfs`)
* removed `debug.py`, I would suggest to handle this in a separate PR in the context of this issue: changegrote/osm2gtfs/issues/46 (there is some starting work in the branch `issue-46-debug` in [my repo](https://github.com/xamanu/osm2gtfs/tree/issue-46-debug)
* fixed accra GTFS generation. At least it ran through without any errors now.

### CODE REVIEW

**Comment by xamanu** [comment]
* I re-added the `debug.py` as (after a comment in grote/osm2gtfs/issues/46) as we probably have to think a bit more about what to do here. And we probably don't want to loose the `print_shape_for_leaflet` function.
* I tried to clean-up the commits and their descriptions.

**Comment by xamanu** [comment]
This can probably not be merged, due to conflicts and the earlier commit I renamed. But with a forced push it will be all good :smile:

**Comment by AltNico** [comment]
Thanks a lot for your work on this. Sadly, I will not have time to review the changes until next week, so feel free to push to my branch directly (I guess you can because of GitHub's allow edits by maintainers policy) or open a new pull request to move forward quickly.

**Comment by xamanu** [comment]
Thanks, @AltNico, I was not able to push to your branch. And I did a pull re-request: https://github.com/grote/osm2gtfs/pull/84

**Pull request closed without merging**
